apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-yaml
    method: fromcode
    another: label
    another: label2
  name: nginx-yaml
spec:
  containers:
  - image: nginx
    name: nginx-yaml
